name: Frontend Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint JavaScript
        run: npx eslint ./src/main/resources/static/js/**/*.js

      - name: Lint CSS
        run: npx stylelint ./src/main/resources/static/css/**/*.css

      - name: Lint HTML
        run: npx htmlhint ./src/main/resources/templates/**/*.html
